#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var docopt, fs, chalk, doc, getOption, o, message, diff, f1, f2, v;
  docopt = require('docopt').docopt;
  fs = require('fs');
  chalk = require('chalk');
  doc = "Usage:\n    diff-files FILE1 FILE2 [ -m MSG ]\n    diff-files -h | --help \n\nOptions:\n    -m , --message MSG      Print optional message when running the script";
  getOption = function(a, b, def, o){
    if (!o[a] && !o[b]) {
      return def;
    } else {
      return o[b];
    }
  };
  o = docopt(doc);
  message = getOption('-m', '--message', '', o);
  diff = require('diff');
  f1 = fs.readFileSync(o['FILE1'], 'utf-8');
  f2 = fs.readFileSync(o['FILE2'], 'utf-8');
  v = diff.diffLines(f1, f2);
  if (v.length === 1 && v[0].count == null && v[0].added == null && v[0].removed == null) {
    console.error((message + ": ") + chalk.green('OK'));
  } else {
    console.error((message + ": ") + chalk.red('FAIL'));
  }
}).call(this);
